'use client'

import { useEffect, useState } from 'react'

interface Progress { judgeId: string; name: string | null; email: string | null; assigned: number; completed: number; pending: number; progressPercent: number }
interface Dashboard { totalJudges: number; totalAssignments: number; completedEvaluations: number; pendingEvaluations: number; overallProgress: number; perJudgeProgress: Progress[] }

export default function OrganizerJudgingPage() {
  const [eventId, setEventId] = useState('')
  const [data, setData] = useState<Dashboard | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { const id = new URLSearchParams(window.location.search).get('eventId') ?? ''; setEventId(id) }, [])
  useEffect(() => { if (!eventId) return; fetch(`/api/organizer/judging/dashboard?eventId=${encodeURIComponent(eventId)}`).then(async (r) => { if (!r.ok) throw new Error('Unable to load judging dashboard'); return r.json() }).then(setData).catch((e: Error) => setError(e.message)) }, [eventId])
  return <main className="min-h-screen bg-[#f7f8fb] px-6 py-10 text-[#181a20] md:px-12"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#635bdb]">Organizer / Judging</p><div className="mt-3 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-4xl font-bold tracking-tight">Judging management</h1><p className="mt-2 text-sm text-[#737783]">Monitor assignment coverage and evaluation progress.</p></div><a className="rounded-xl bg-[#635bdb] px-4 py-2.5 text-center text-sm font-bold text-white" href={eventId ? `/api/organizer/export?eventId=${encodeURIComponent(eventId)}` : '#'}>Export CSV</a></div>{error && <p role="alert" className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Judges" value={data?.totalJudges ?? '—'} /><Metric label="Assignments" value={data?.totalAssignments ?? '—'} /><Metric label="Completed" value={data?.completedEvaluations ?? '—'} /><Metric label="Pending" value={data?.pendingEvaluations ?? '—'} /><Metric label="Progress" value={data ? `${Math.round(data.overallProgress)}%` : '—'} /></div><section className="mt-8 overflow-hidden rounded-2xl border border-[#e6e7ed] bg-white"><div className="border-b border-[#eef0f4] p-5"><h2 className="text-lg font-bold">Judge progress</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="bg-[#fafafd] text-xs text-[#858894]"><tr><th className="px-5 py-3">Judge</th><th className="px-5 py-3">Assigned</th><th className="px-5 py-3">Completed</th><th className="px-5 py-3">Pending</th><th className="px-5 py-3">Progress</th></tr></thead><tbody>{data?.perJudgeProgress.map((judge) => <tr key={judge.judgeId} className="border-t border-[#eef0f4]"><td className="px-5 py-4 font-semibold">{judge.name ?? judge.email ?? judge.judgeId}</td><td className="px-5 py-4">{judge.assigned}</td><td className="px-5 py-4">{judge.completed}</td><td className="px-5 py-4">{judge.pending}</td><td className="px-5 py-4 font-semibold">{Math.round(judge.progressPercent)}%</td></tr>)}</tbody></table>{data && data.perJudgeProgress.length === 0 && <p className="p-8 text-sm text-[#858894]">No judges or assignments found.</p>}</div></section></div></main>}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl border border-[#e6e7ed] bg-white p-5"><p className="text-xs font-semibold text-[#858894]">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div> }
